apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legacy-web-service.fullname" . }}-secret
  labels:
    {{- include "legacy-web-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
